### ISSUE TITLE
Incorrect event source determination 

### ISSUE THREAD

**Issue by IlyaHancharTR** [DataDog/datadog-serverless-functions#284] opened 2020-06-19 13:36 UTC
# What happened

In case lambda name contains `dms` forwarder incorrectly determines that the event came from `AWS Database Migration`

I guess the error occurs due to an incorrect logic in the function `parse_event_source(event, key)`

# Expected Behavior

Forwarder should determine that the event comes from `lambda`

# Steps to reproduce the issue

Create any `lambda` that contains one of the suggested substring in the name.
Then try to process the logs that produce this lambda.

If name contains `dms` then forwarder determines that event comes from `AWS Database Migration`
If name contains `codebuild` then forwarder determines that event comes from `AWS CodeBuild`

# Specifications

Forwarder version: 3.13.0

**Comment by tianchu** [comment] 2020-06-19 14:10
@IlyaHancharTR thanks for the bug report, we will have someone look into it. But it sounds like you already found the cause, wondering do you have a proposed PR to fix the issue?

**Comment by IlyaHancharTR** [comment] 2020-07-10 15:23
@tianchu Yes, I found the solution for my cases, but I don't know if my fix will work for all the possible scenarios. I didn't find any tests covering this function.

**Comment by tianchu** [comment] 2020-09-22 01:33
cc: @DylanLovesCoffee in case you can factor this issue in you on-going attempt to improve source determination? I believe for lambda logs, we should be reliably determine the source being lambda based on the log group name pattern.

**Comment by tianchu** [comment] 2020-11-03 15:21
I believe this issue has been resolved by #365.

**Closed as completed by tianchu** 2020-11-03 15:21 UTC
